import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router";
import { X, GitCompareArrows, ChevronRight, AlertCircle } from "lucide-react";
import { useApp } from "../context/AppContext";
import { motion, AnimatePresence } from "motion/react";
export function CompareBar() {
    const navigate = useNavigate();
    const { compareList, removeFromCompare, clearCompare, compareTradeSlug } = useApp();
    const handleCompare = () => {
        const toolIds = compareList.map((t) => t.id).join(",");
        const tradeParam = compareTradeSlug ? `&trade=${compareTradeSlug}` : "";
        navigate(`/compare?tools=${toolIds}${tradeParam}`);
    };
    return (_jsx(AnimatePresence, { children: compareList.length > 0 && (_jsx(motion.div, { initial: { y: 100, opacity: 0 }, animate: { y: 0, opacity: 1 }, exit: { y: 100, opacity: 0 }, transition: { type: "spring", stiffness: 400, damping: 30 }, className: "fixed bottom-0 left-0 right-0 z-50 shadow-2xl border-t", style: { backgroundColor: "#0c1a2e", borderColor: "#1e3a5f" }, children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3", children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "flex items-center gap-2 shrink-0", children: [_jsx(GitCompareArrows, { className: "w-4 h-4", style: { color: "#f97316" } }), _jsxs("span", { className: "text-sm font-semibold text-white", children: ["Compare (", compareList.length, "/4)"] })] }), _jsxs("div", { className: "flex-1 flex items-center gap-2 overflow-x-auto scrollbar-none py-1", children: [compareList.map((tool) => (_jsxs("div", { className: "flex items-center gap-2 px-3 py-1.5 rounded-full border shrink-0", style: { backgroundColor: "rgba(255,255,255,0.06)", borderColor: "#1e3a5f" }, children: [_jsx("div", { className: "w-5 h-5 rounded flex items-center justify-center text-white text-xs font-bold shrink-0", style: { backgroundColor: tool.logoColor }, children: tool.logoInitials[0] }), _jsx("span", { className: "text-xs text-white whitespace-nowrap", children: tool.name }), _jsx("button", { onClick: () => removeFromCompare(tool.id), className: "hover:text-red-400 transition-colors", style: { color: "#64748b" }, children: _jsx(X, { className: "w-3 h-3" }) })] }, tool.id))), compareList.length < 4 && (_jsx("div", { className: "flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-dashed shrink-0", style: { borderColor: "#334155" }, children: _jsxs("span", { className: "text-xs", style: { color: "#475569" }, children: ["Add up to ", 4 - compareList.length, " more"] }) }))] }), compareList.length < 2 && (_jsxs("div", { className: "hidden sm:flex items-center gap-1 shrink-0", children: [_jsx(AlertCircle, { className: "w-3.5 h-3.5", style: { color: "#64748b" } }), _jsx("span", { className: "text-xs", style: { color: "#64748b" }, children: "Select at least 2" })] })), _jsxs("div", { className: "flex items-center gap-2 shrink-0", children: [_jsx("button", { onClick: clearCompare, className: "text-xs px-3 py-1.5 rounded-lg border transition-colors hover:bg-white/5", style: { borderColor: "#1e3a5f", color: "#64748b" }, children: "Clear" }), _jsxs("button", { onClick: handleCompare, disabled: compareList.length < 2, className: "flex items-center gap-1.5 text-sm font-medium text-white px-4 py-2 rounded-xl transition-all hover:brightness-110 disabled:opacity-40 disabled:cursor-not-allowed", style: { backgroundColor: "#f97316" }, children: ["Compare Now", _jsx(ChevronRight, { className: "w-4 h-4" })] })] })] }) }) })) }));
}
