import type { Project, ProjectReference, Task } from './types';

export const initialProjects: Project[] = [
  { id: 'p1', name: 'Website Foundation', status: 'on-track' },
  { id: 'p2', name: 'SEO Content Wave 1', status: 'at-risk' },
  { id: 'p3', name: 'Launch QA + Tracking', status: 'on-track' },
  { id: 'p4', name: 'Memory System Rollout', status: 'on-track' },
  { id: 'p5', name: 'Website Launch Sprint', status: 'at-risk' },
];

export const initialTasks: Task[] = [
  {
    id: 'mem-01',
    projectId: 'p4',
    title: 'Define why agent memory fails',
    owner: 'Henry',
    status: 'progress',
    estimateHours: 2,
    remainingHours: 1.5,
    currentWork: 'Drafting failure-mode brief',
    details: 'Create team brief on core failure causes and examples.',
    eta: 'TBD',
  },
  {
    id: 'mem-02',
    projectId: 'p4',
    title: 'Implement quick-start 3 memory controls',
    owner: 'Elliot',
    status: 'progress',
    estimateHours: 3,
    remainingHours: 2.5,
    currentWork: 'Setting baseline controls',
    details: 'Set baseline controls that prevent common forgetting patterns.',
    eta: 'TBD',
  },
  {
    id: 'mem-03',
    projectId: 'p4',
    title: 'Document 4 memory types',
    owner: 'Leslie',
    status: 'progress',
    estimateHours: 2,
    remainingHours: 1.5,
    currentWork: 'Writing memory-type definitions',
    details: 'Define and teach distinctions clearly to all agents.',
    eta: 'TBD',
  },
  {
    id: 'mem-04',
    projectId: 'p4',
    title: 'Audit 3 memory failure modes',
    owner: 'Dexter',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Run tests and list failure cases with reproduction steps.',
    eta: 'TBD',
  },
  {
    id: 'mem-05',
    projectId: 'p4',
    title: 'Set compaction vs pruning policy',
    owner: 'Spock',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Establish architecture decision and operating guidelines.',
    eta: 'TBD',
  },
  {
    id: 'mem-06',
    projectId: 'p4',
    title: 'Add /context list verification step',
    owner: 'Elliot',
    status: 'todo',
    estimateHours: 1,
    remainingHours: 1,
    currentWork: 'Queued',
    details: 'Operational check to prove loaded context before key actions.',
    eta: 'TBD',
  },
  {
    id: 'mem-07',
    projectId: 'p4',
    title: 'Document compaction behavior',
    owner: 'Leslie',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Clarify what compaction preserves vs what it discards.',
    eta: 'TBD',
  },
  {
    id: 'mem-08',
    projectId: 'p4',
    title: 'Enable pre-compaction memory flush',
    owner: 'Henry',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Ensure durable write before compaction events.',
    eta: 'TBD',
  },
  {
    id: 'mem-09',
    projectId: 'p4',
    title: 'Enable manual saves + /compact trick',
    owner: 'Henry',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Codify operator workflow for resilient continuity.',
    eta: 'TBD',
  },
  {
    id: 'mem-10',
    projectId: 'p4',
    title: 'Implement file architecture standard',
    owner: 'Spock',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Define layout, naming, and lifecycle of memory files.',
    eta: 'TBD',
  },
  {
    id: 'mem-11',
    projectId: 'p4',
    title: 'Add AGENTS.md memory protocol',
    owner: 'Leslie',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Embed memory rules and retrieval discipline instructions.',
    eta: 'TBD',
  },
  {
    id: 'mem-12',
    projectId: 'p4',
    title: 'Implement retrieval modes A / A+ / QMD',
    owner: 'Lisbeth',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Test retrieval quality, coverage, and precision settings.',
    eta: 'TBD',
  },
  {
    id: 'mem-13',
    projectId: 'p4',
    title: 'Add cost and cache monitoring',
    owner: 'Marty',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Track performance and token/cost implications weekly.',
    eta: 'TBD',
  },
  {
    id: 'mem-14',
    projectId: 'p4',
    title: 'Apply complete memory config baseline',
    owner: 'Elliot',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Deploy copy-and-go configuration across workspace.',
    eta: 'TBD',
  },
  {
    id: 'mem-15',
    projectId: 'p4',
    title: 'Publish 5-things-to-remember cheat sheet',
    owner: 'Henry',
    status: 'todo',
    estimateHours: 1,
    remainingHours: 1,
    currentWork: 'Queued',
    details: 'Create concise team-facing reference for daily use.',
    eta: 'TBD',
  },
  {
    id: 'web-01',
    projectId: 'p5',
    title: 'Lock first-wave publish list (10 URLs)',
    owner: 'Henry',
    status: 'progress',
    estimateHours: 2,
    remainingHours: 1,
    currentWork: 'Prioritizing high-intent pages',
    details: 'Finalize exact first 10 URLs and handoff order.',
    eta: 'Today',
  },
  {
    id: 'web-02',
    projectId: 'p5',
    title: 'Validate keyword difficulty + intent for first wave',
    owner: 'Lisbeth',
    status: 'progress',
    estimateHours: 4,
    remainingHours: 2.5,
    currentWork: 'Scoring first-wave targets',
    details: 'Add confidence score and competition notes to each target.',
    eta: 'Today',
  },
  {
    id: 'web-03',
    projectId: 'p5',
    title: 'Finalize first 3 production briefs',
    owner: 'Leslie',
    status: 'progress',
    estimateHours: 4,
    remainingHours: 2,
    currentWork: 'Converting draft briefs to production format',
    details: 'Include acceptance criteria, sections, schema, CTA, FAQs.',
    eta: 'Today',
  },
  {
    id: 'web-04',
    projectId: 'p5',
    title: 'Design page template v1 (guide + compare)',
    owner: 'Don',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Deliver responsive template spec for implementation.',
    eta: 'Today',
  },
  {
    id: 'web-05',
    projectId: 'p5',
    title: 'Build template components in Next.js',
    owner: 'Elliot',
    status: 'todo',
    estimateHours: 6,
    remainingHours: 6,
    currentWork: 'Queued',
    details: 'Implement reusable sections for product/comparison pages.',
    eta: 'Today',
  },
  {
    id: 'web-06',
    projectId: 'p5',
    title: 'Architecture sanity pass on content model',
    owner: 'Spock',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Validate schema strategy and URL conventions before scale.',
    eta: 'Today',
  },
  {
    id: 'web-07',
    projectId: 'p5',
    title: 'QA gate checklist per page type',
    owner: 'Dexter',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Define pass/fail checks for content, links, mobile, speed, tracking.',
    eta: 'Today',
  },
  {
    id: 'web-08',
    projectId: 'p5',
    title: 'SEO metadata + schema standard',
    owner: 'Olivia',
    status: 'todo',
    estimateHours: 3,
    remainingHours: 3,
    currentWork: 'Queued',
    details: 'Apply title/meta/FAQ/Product schema conventions.',
    eta: 'Today',
  },
  {
    id: 'web-09',
    projectId: 'p5',
    title: 'Measurement events and dashboard baseline',
    owner: 'Marty',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Track CTA clicks, scroll depth, engagement, and conversion events.',
    eta: 'Today',
  },
  {
    id: 'web-10',
    projectId: 'p5',
    title: 'Research top 5–7 apps per trade (all 16 trades)',
    owner: 'Lisbeth',
    status: 'todo',
    estimateHours: 8,
    remainingHours: 8,
    currentWork: 'Queued',
    details: 'Compile shortlist and source-backed rationale per trade.',
    eta: 'Today',
  },
  {
    id: 'web-11',
    projectId: 'p5',
    title: 'Create product pages with pros/cons (wave 1)',
    owner: 'Leslie',
    status: 'todo',
    estimateHours: 10,
    remainingHours: 10,
    currentWork: 'Queued',
    details: 'Write first 10 software pages with standardized structure.',
    eta: 'This week',
  },
  {
    id: 'web-12',
    projectId: 'p5',
    title: 'Internal linking map for launch wave',
    owner: 'Olivia',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Connect guides, comparisons, and trade hubs for crawl depth.',
    eta: 'Today',
  },
  {
    id: 'web-13',
    projectId: 'p5',
    title: 'Content + page QA on first 3 URLs',
    owner: 'Dexter',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Run full QA before first publish.',
    eta: 'Today',
  },
  {
    id: 'web-14',
    projectId: 'p5',
    title: 'Publish first 3 pages',
    owner: 'Elliot',
    status: 'todo',
    estimateHours: 2,
    remainingHours: 2,
    currentWork: 'Queued',
    details: 'Deploy and verify pages render + events fire.',
    eta: 'Today',
  },
  {
    id: 'web-15',
    projectId: 'p5',
    title: 'Post-launch performance snapshot (24h)',
    owner: 'Marty',
    status: 'todo',
    estimateHours: 1,
    remainingHours: 1,
    currentWork: 'Queued',
    details: 'Report impressions, CTR, engagement, and first anomalies.',
    eta: 'Tomorrow',
  },
];

export const initialReferences: ProjectReference[] = [];

// Dependency map for blocker visibility in Mission Control.
export const taskDependencies: Record<string, string[]> = {
  'web-03': ['web-02'],
  'web-04': ['web-01', 'web-03'],
  'web-05': ['web-04'],
  'web-06': ['web-01', 'web-03'],
  'web-07': ['web-04', 'web-05', 'web-08'],
  'web-08': ['web-03'],
  'web-09': ['web-05'],
  'web-11': ['web-02', 'web-03', 'web-10'],
  'web-12': ['web-03'],
  'web-13': ['web-05', 'web-07', 'web-08', 'web-12'],
  'web-14': ['web-13', 'web-09'],
  'web-15': ['web-14'],
};
